apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 500Mi  # Adjust the size as per your requirement
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /d/sanchit/programming_shit/AIML/dockerok/src/static/uploads  # Replace with your actual host path
