apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app-container
  ports:
  - port: 6000
    targetPort: 5000
    nodePort: 32188    # Add this line to specify the NodePort
  type: NodePort       # Change the service type to NodePort
